services:
  - type: web
    name: your-app-name  # Replace with your app's name
    env: python
    runtime: python3
    buildCommand: |
      pip install -r requirements.txt
      playwright install-deps
      playwright install chromium
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
